services:
  nginx:
    profiles: ["standard"]
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: devsecops-nginx:standard
    ports:
      - "8080:80"

  nginx-secure:
    profiles: ["secure"]
    build:
      context: .
      dockerfile: Dockerfile.nginx.secure
    image: devsecops-nginx:secure

  python:
    profiles: ["standard"]
    build:
      context: .
      dockerfile: Dockerfile.python
    image: devsecops-python:standard
    depends_on:
      - nginx

  python-secure:
    profiles: ["secure"]
    build:
      context: .
      dockerfile: Dockerfile.python.secure
    image: devsecops-python:secure
    depends_on:
      - nginx-secure
