FROM nginx:stable-alpine

RUN addgroup -S app && adduser -S app -G app

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/index.html /usr/share/nginx/html/index.html

RUN chown -R app:app \
    /usr/share/nginx \
    /var/cache/nginx \
    /etc/nginx

USER app
EXPOSE 80